<a href="https://colab.research.google.com/github/AR-Ashik-9997/Phitron-practice-problem/blob/main/Mushroom_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Required Libraries

In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score,recall_score,classification_report

Load Dataset

In [41]:
df=pd.read_csv('/content/mushrooms.csv')
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

Data Preprocessing

In [42]:
df.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring    8124 non-null   object
 15  stalk-color-below-ring    8124 non-null   object
 16  veil-type                 8124 non-null   object
 17  veil-color                8124 non-null   object
 18  ring-number               8124 non-null   object
 19  ring-type                 8124 non-null   object
 20  spore-print-color         8124 non-null   object
 21  population                8124 non-null   object
 22  habitat                   8124 non-null   object
dtypes: object(23)
memory usage: 1.4+ MB

In [44]:
df.duplicated().sum()

np.int64(0)

Feature & Target Separation

In [45]:
X=df.drop('class',axis=1)
y=df['class']

## Encoding

In [46]:
le=LabelEncoder()
y_encode=le.fit_transform(y)

Data Splitting

In [47]:
X_train,X_test,y_train,y_test=train_test_split(X,y_encode,test_size=0.2,random_state=42)

Categorical Feature

In [48]:
cat_feature=X.columns.to_list()

Preprocessor

In [49]:
preprocessor=ColumnTransformer(
    transformers=[
        ('cat',OneHotEncoder(drop='first',handle_unknown='ignore'),cat_feature)
    ],
    remainder='passthrough'
)

Model Building

In [50]:
svc_pipeline=Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('classifier',SVC(kernel='linear',random_state=42))
    ]
)
svc_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['cap-shape', 'cap-surface',
                                                   'cap-color', 'bruises',
                                                   'odor', 'gill-attachment',
                                                   'gill-spacing', 'gill-size',
                                                   'gill-color', 'stalk-shape',
                                                   'stalk-root',
                                                   'stalk-surface-above-ring',
                                                   'stalk-surface-below-ring',
                                                   'stalk-color-above-ring',
                                                   'stalk-color-below-ring',
                                                   'veil-type', 'veil-color',
                                                   'ring-number', 'ring-type',
                                                   'spore-print-color',
                                                   'population',
                                                   'habitat'])])),
                ('classifier', SVC(kernel='linear', random_state=42))])

Evaluting

In [51]:
y_pred = svc_pipeline.predict(X_test)
acc=accuracy_score(y_test,y_pred)
prec=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)
classification=classification_report(y_test,y_pred)

print(f'Accuracy: {acc*100:.2f}%')
print(f'Precision Score: {prec*100:.2f}%')
print(f'Recall Score: {recall*100:.2f}%')
print("\n",classification)

Accuracy: 100.00%
Precision Score: 100.00%
Recall Score: 100.00%

               precision    recall  f1-score   support

           0       1.00      1.00      1.00       843
           1       1.00      1.00      1.00       782

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625

In [52]:
DT_pipeline=Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('classifier',DecisionTreeClassifier(random_state=42))
    ]
)
DT_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['cap-shape', 'cap-surface',
                                                   'cap-color', 'bruises',
                                                   'odor', 'gill-attachment',
                                                   'gill-spacing', 'gill-size',
                                                   'gill-color', 'stalk-shape',
                                                   'stalk-root',
                                                   'stalk-surface-above-ring',
                                                   'stalk-surface-below-ring',
                                                   'stalk-color-above-ring',
                                                   'stalk-color-below-ring',
                                                   'veil-type', 'veil-color',
                                                   'ring-number', 'ring-type',
                                                   'spore-print-color',
                                                   'population',
                                                   'habitat'])])),
                ('classifier', DecisionTreeClassifier(random_state=42))])

In [53]:
dt_y_pred = DT_pipeline.predict(X_test)
acc=accuracy_score(y_test,dt_y_pred)
prec=precision_score(y_test,dt_y_pred)
recall=recall_score(y_test,dt_y_pred)
classification_dt=classification_report(y_test,dt_y_pred)

print(f'Accuracy: {acc*100:.2f}%')
print(f'Precision Score: {prec*100:.2f}%')
print(f'Recall Score: {recall*100:.2f}%')
print("\n",classification_dt)

Accuracy: 100.00%
Precision Score: 100.00%
Recall Score: 100.00%

               precision    recall  f1-score   support

           0       1.00      1.00      1.00       843
           1       1.00      1.00      1.00       782

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625

## overfitting Testing

In [54]:
train_pred = DT_pipeline.predict(X_train)
train_acc = accuracy_score(y_train, train_pred)

test_pred = DT_pipeline.predict(X_test)
test_acc = accuracy_score(y_test, test_pred)

overfitting_test=train_acc-test_acc
if(overfitting_test>0.5*100):
  print(f"overfitting percentage: {overfitting_test*100:.2f}%")
else:
  print("No overfitting")

No overfitting

Since both the Linear SVM and Decision Tree models achieved 100% accuracy, precision, and recall on the test set, it demonstrates that the **Kaggle** Mushroom dataset is perfectly structured and linearly separable after One-Hot Encoding.